// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDskC4l3NXsF_MvyS-p7M3piz5uR9zsD4',
    appId: '1:807039639077:android:c65e4ee3a6ec5e887f29cc',
    messagingSenderId: '807039639077',
    projectId: 'plantpal-46483',
    storageBucket: 'plantpal-46483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlUvqsiKpefG3aIf7oOtGhTepBaWjF1U',
    appId: '1:807039639077:ios:b464987928234b2a7f29cc',
    messagingSenderId: '807039639077',
    projectId: 'plantpal-46483',
    storageBucket: 'plantpal-46483.appspot.com',
    androidClientId: '807039639077-5k3g47qbvpdudcgd0d8tgohe94f0h95n.apps.googleusercontent.com',
    iosClientId: '807039639077-em8ru4ho8o6o1vdaa1b3u6na6h0lf99t.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantPulse',
  );
}
